language: cpp
install: ./gen-unix.sh
compiler: gcc
before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq [packages list]
git:
  depth: 3
# whitelist
branches:
  only:
    - master
    - develop
    - /^feature-.*$/
