language: cpp
addons:
  apt:
    packages:
#      - valgrind
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test

install:
- ./gen-unix.sh
compiler:
- gcc
before_install:
- sudo ./install-dependencies.sh
- export WITHOUT_MARKLOGIC=1
git:
  depth: 3
#os:
#- linux
#- osx
matrix:
  include:
    # GCC 6
    - os: linux
      env: COMPILER=g++-6 BOOST_VERSION=default
      compiler: gcc

    # Clang 3.8
    - os: linux
      env: LLVM_VERSION=3.8.0 BOOST_VERSION=default
      compiler: clang

    # Xcode 7.3
    - os: osx
      env: BOOST_VERSION=default
      osx_image: xcode7.3
      
script:
- ./build.sh && cd ./bin/test && ./mlcpptest
branches:
  only:
  - master
  - develop
  - feature-24
